
import React, { useState, useRef, useEffect } from 'react';
import { Download, FileText, FileJson, FileType, ChevronDown, Share } from 'lucide-react';
import { ResearchMode, ResearchDocument } from '../types';
import { MODES } from '../constants';

interface ExportMenuProps {
  inputText: string;
  analysisContent: string;
  mode: ResearchMode;
  documents: ResearchDocument[];
  disabled?: boolean;
}

export const ExportMenu: React.FC<ExportMenuProps> = ({ 
  inputText, 
  analysisContent, 
  mode, 
  documents, 
  disabled 
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  // Close menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const generateFilename = (extension: string) => {
    const date = new Date().toISOString().split('T')[0];
    const timestamp = new Date().toTimeString().split(' ')[0].replace(/:/g, '-');
    return `Research-Session-${date}-${timestamp}.${extension}`;
  };

  const downloadFile = (content: string, type: string, extension: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = generateFilename(extension);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    setIsOpen(false);
  };

  const handleExportMarkdown = () => {
    const modeConfig = MODES[mode];
    const timestamp = new Date().toLocaleString();
    
    const fileList = documents.length > 0 
      ? documents.map(d => `- ${d.title} (${d.type.toUpperCase()})`).join('\n')
      : 'None';

    const content = `# Research Session Artifact
**Date:** ${timestamp}
**Mode:** ${modeConfig.title} (${modeConfig.subtitle})
**Context Files:**
${fileList}

---

## Research Query
${inputText || '(No query text provided)'}

## Analysis Output
${analysisContent || '(No analysis generated)'}

---
*Generated by The Research Companion*
`;
    downloadFile(content, 'text/markdown', 'md');
  };

  const handleExportText = () => {
    const modeConfig = MODES[mode];
    const timestamp = new Date().toLocaleString();
    const fileList = documents.length > 0 
      ? documents.map(d => d.title).join(', ')
      : 'None';

    const content = `RESEARCH SESSION LOG
====================
Date: ${timestamp}
Mode: ${modeConfig.title}
Files: ${fileList}

QUERY:
--------------------
${inputText}

ANALYSIS:
--------------------
${analysisContent}
`;
    downloadFile(content, 'text/plain', 'txt');
  };

  const handleExportJSON = () => {
    const data = {
      timestamp: Date.now(),
      dateReadable: new Date().toLocaleString(),
      mode,
      modeDetails: MODES[mode],
      contextFiles: documents.map(d => ({ title: d.title, type: d.type, id: d.id })),
      query: inputText,
      analysis: analysisContent
    };
    downloadFile(JSON.stringify(data, null, 2), 'application/json', 'json');
  };

  return (
    <div className="relative" ref={menuRef}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        disabled={disabled}
        className={`
          flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-semibold border transition-all
          ${disabled 
            ? 'bg-slate-100 text-slate-400 border-slate-200 cursor-not-allowed' 
            : 'bg-white text-slate-700 border-slate-200 hover:bg-slate-50 hover:border-slate-300 hover:text-slate-900 shadow-sm'
          }
        `}
      >
        <Share size={14} />
        <span className="hidden sm:inline">Export</span>
        <ChevronDown size={12} className={`transition-transform ${isOpen ? 'rotate-180' : ''}`} />
      </button>

      {isOpen && !disabled && (
        <div className="absolute right-0 mt-2 w-56 bg-white rounded-xl shadow-xl border border-slate-100 ring-1 ring-black/5 z-50 overflow-hidden animate-in fade-in zoom-in-95 duration-100">
          <div className="p-2 border-b border-slate-50 bg-slate-50/50">
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider px-2">Select Format</p>
          </div>
          <div className="p-1">
            <button 
              onClick={handleExportMarkdown}
              className="w-full text-left flex items-center gap-3 px-3 py-2 text-sm text-slate-700 hover:bg-slate-50 hover:text-slate-900 rounded-lg transition-colors"
            >
              <div className="p-1.5 bg-slate-100 rounded-md text-slate-500"><FileText size={16} /></div>
              <div>
                <span className="font-medium block">Markdown</span>
                <span className="text-[10px] text-slate-400 block">For Obsidian / Notion</span>
              </div>
            </button>
            
            <button 
              onClick={handleExportText}
              className="w-full text-left flex items-center gap-3 px-3 py-2 text-sm text-slate-700 hover:bg-slate-50 hover:text-slate-900 rounded-lg transition-colors"
            >
               <div className="p-1.5 bg-slate-100 rounded-md text-slate-500"><FileType size={16} /></div>
               <div>
                <span className="font-medium block">Plain Text</span>
                <span className="text-[10px] text-slate-400 block">Standard .txt file</span>
              </div>
            </button>

            <button 
              onClick={handleExportJSON}
              className="w-full text-left flex items-center gap-3 px-3 py-2 text-sm text-slate-700 hover:bg-slate-50 hover:text-slate-900 rounded-lg transition-colors"
            >
               <div className="p-1.5 bg-slate-100 rounded-md text-slate-500"><FileJson size={16} /></div>
               <div>
                <span className="font-medium block">JSON Data</span>
                <span className="text-[10px] text-slate-400 block">Raw structured data</span>
              </div>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
